### ISSUE TITLE
Feature request: support bower package management

### ISSUE THREAD

**Issue by paucls** [ggoodman/angular-drag-drop#14]
This is a great angular drag and drop directive. It would be great if the project can be used also as a bower dependency.

**Comment by curiosity26** [comment]
+1

**Comment by ggoodman** [comment]
@paucls I'm personally not a bower user and do not have the bandwidth to research what needs to be done to add support.

Can you take charge of this? I'll review your PR.

**Comment by paucls** [comment]
Hi @ggoodman,
created a PR to support bower
https://github.com/ggoodman/angular-drag-drop/pull/19

It is working fine for me, I published it in my private bower registry and using it. Please check that this change does not break the webpack version and you still can use it with webpack.

**Comment by ddperdue** [comment]
+1
