### ISSUE TITLE
feature request: simple but full example without webpack and browserify

### ISSUE THREAD

**Issue by alberthendriks** [ggoodman/angular-drag-drop#4]
I would like to have a very simple but full example (i.e. html including all necessary files), but _without webpack and browserify_. I can get the Dragular demo to work on my local machine, but I don't see how to extract the minimally required code.
I'm new to Angular and I can't get it to work. I have:

odds.js:

``` javascript
function(){                                                                     
    var app = angular.module('pokerApp', ['angular-drag-drop']);    
})();
```

I included one of the dist files in my html file but it doesn't work. I get: 

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module pokerApp due to:
Error: [$injector:modulerr] Failed to instantiate module angular-drag-drop due to:
Error: [$injector:nomod] Module 'angular-drag-drop' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

For completeness, I also include my html

``` html
<!DOCTYPE html>
<html lang="en">

<head>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.js"></script>
        <script src="lib/angular-drag-drop.min.js"></script>
        <script src="odds.js"></script>
</head>

<body>

      <div ng-app = "pokerApp" ng-init = "cards = ['As','Ks','Qs','Js','Ts','9s','8s','7s','6s','5s','4s','3s','2s',
                                     'Ah','Kh','Qh','Jh','Th','9h','8h','7h','6h','5h','4h','3h','2h',
                                     'Ad','Kd','Qd','Jd','Td','9d','8d','7d','6d','5d','4d','3d','2d',
                                     'Ac','Kc','Qc','Jc','Tc','9c','8c','7c','6c','5c','4c','3c','2c']"> 

<!--<div drag-container>KKKKKKKKKKKK</div>-->

<!--
<div drag-container="model"
  on-drag-start="ctl.handleDragStart($event, data)"
  on-drag-end="ctl.handleDragEnd($event, data)"
></div>-->
</div>

    </body>
</html>
```

**Comment by ggoodman** [comment]
Hi @alberthendriks, please try using:

``` js
function(){                                                                     
    var app = angular.module('pokerApp', ['filearts.dragDrop']);    
})();
```

**Comment by alberthendriks** [comment]
It's not working, see http://run.plnkr.co/plunks/7S3BFW/
Still the same error.

**Comment by ggoodman** [comment]
The issue you are having is because `angular-drag-drop` is packaged as a `UMD` module (which supports commonJS, requireJS and browser environments).

Your code is loading `html
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.22/require.js"></script>`

and this is causing the UMD loader to export the module using `require.js` instead of immediately exposing it at `window.AngularDragDrop`.

Try removing the `require.js`loader or putting it after angular and `angular-drag-drop`.

**Comment by alberthendriks** [comment]
Thanks!! It works now.
