### ISSUE TITLE
dataTransfer.setData() and getData() not too useful as it now stands

### ISSUE THREAD

**Issue by bradacina** [ggoodman/angular-drag-drop#6]
The DnD spec is not very useful as it stands now. Setting setData in drag-start works fine but trying to retrieve the data in drag-end, drag-over , etc. will not give you back the data since you are in protected mode.

See:
http://stackoverflow.com/questions/11927309/html5-dnd-datatransfer-setdata-or-getdata-not-working-in-every-browser-except-fi

There should be a different mechanism to attach data, probably using a directive local variable.
This could also be useful for attaching mime/types to drag areas and attaching accept types to drop areas.

**Comment by ggoodman** [comment]
Hi @bradacina `v2.0.0`, the `dragData` API is not used at all internally. Users are open to leveraging it by  using `drag-start` handlers that take the `$event` object and accessing `dragData` that way.

As you can see here https://github.com/ggoodman/angular-drag-drop/blob/master/src/angular-drag-drop.js#L55-L62, `angular-drag-drop` is using an Angular _Service_ as the storage mechanism for the drag state.

Because of this, I'm closing this issue. Please let me know if there are further problems related to the spec.

**Comment by bradacina** [comment]
The use case I'm looking at in particular is one page with multiple drag-container areas and multiple drop-container areas. Not only do I need the drag-data but also I need a way to specify which drag-container data can be dropped on which drop-container. In my case there is an intermingle of dragarea1 items being able to be dropped on droparea1 and droparea2, droparea3 accepting dragarea2 and dragarea3 items. In the previous version of the library this was made pretty straight forward by the use of the "mime-type" attribute in drag areas and "accepts" attribute in drop areas.

Can you suggest a way to achieve this in a similar fashion with the current version of the library but without polluting the drag-data with an attribute called mimetype or datatype or similar.

For now I resorted to modifying the library and storing in dragContext an extra attribute called mimeType which also gets exposed in all the "locals" next to the $event and $dragData as $mimeType. This way when calling drag-accepts I can pass in the $mimeType and allow the method to determine if it accepts that particular mime type.

Thank you in advance.

**Comment by ggoodman** [comment]
Hi @bradacina I don't see a convincing reason to have two different pieces of drag state. As you mention, if string-based bit of metadata is enough for you to make the decision, then you can easily structure your `dragData` as an object like:

``` js
$scope.dragDataModel = {
  type: 'whatever works',
  value: 'the payload',
};
```

``` html
<div drag-container="dragDataModel"></div>
```

The 'penalty' for this approach is an additional scope value dereference in the drop handler's `drop-accept` and `on-drop` attributes.

``` html
<div drop-container
  drop-accepts="acceptsFunction($dragData.type)"
  on-drop="handleDrop($dragData.value)"
></div>
```

Are there any scenarios that could be accomplished with the `1.x` behaviour that are no longer possible?
