### ISSUE TITLE
npm build doesn't work with browserify

### ISSUE THREAD

**Issue by trakout** [ggoodman/angular-drag-drop#8]
Browserify hangs with no visible output (even with debug: true) if `require('angular-drag-drop');` is used.

Using: https://www.npmjs.com/package/angular-drag-drop#drag-container

Manually changing angular-drag-drop's package JSON to use 'angular-drag-drop.min.js' as main instead of the un-minified version works as a temp fix.

**Comment by trakout** [comment]
update, debug screenshot attached.

![screen shot 2015-12-28 at 4 53 47 pm](https://cloud.githubusercontent.com/assets/1810346/12026121/db0903d2-ad83-11e5-929a-13d5d6f0bfd7.jpg)

**Comment by ggoodman** [comment]
Is this still an issue for you?

**Comment by trakout** [comment]
@ggoodman Yes, upgraded to 2.0.6 (from 2.0.4), still an issue. Maybe it's my gulp scripting? (without posting code, development flow is browserify w/ watchify plugin -> sourcemaps -> uglify -> browsersync) Using minified still fixes it.

**Comment by ggoodman** [comment]
I suspect that the issue has to do w/ the use of `webpack` to generate a UMD. Perhaps a cleaner alternative would be to use plain old javascript to add the minimal required stylesheet dynamically, use a simple UMD wrapper and avoid webpack all-together.

**Comment by ggoodman** [comment]
Hi @trakout can you give #12 a try?

**Comment by trakout** [comment]
@ggoodman apologies for the wait, #12 works like a charm. Thanks!

**Comment by ggoodman** [comment]
Fixed by #12.
