### ISSUE TITLE
Support nested drop containers?

### ISSUE THREAD

**Issue by CobraFlow** [ggoodman/angular-drag-drop#9]
I am trying to nest drop containers and am unable to receive the drop events in the nested container. All events are passed directly to the parent as if the nested control is ignoring them...

Any ideas?

**Comment by ggoodman** [comment]
@CobraFlow this is by design but maybe we should consider having an escape hatch.

Here is why this is happening: https://github.com/ggoodman/angular-drag-drop/blob/master/src/angular-drag-drop.less#L2-L18

As you can see, when `.drag-active` is set on any parent of the `.drop-container`, it will be given `pointer-events: none` and a transparent overlay will be prepended to the element. This is done because if you have any `<iframe>` elements within a `.drop-container` they seem to steal events and prevent the the selection of a `.drop-target`.

I think the current behaviour should remain the default, but it might be worthwhile to add a `angular.config` mechanism so that the behaviour can be disabled. Thoughts?

**Comment by CobraFlow** [comment]
My situation is that I have drop container 'panels' which can be nested to any level.

GrandParent -> Parent -> Child

I think that the topmost (Child above) should receive the drop events by default.
If the child does not cover all of the parent, then the parent should receive the events when the cursor is over any exposed parent.

I would suggest that the <iframe> children should be the exception. Does this happen often?

**Comment by ggoodman** [comment]
@CobraFlow interesting that you find this a limitation in that specific context. I built `angular-drag-drop` specifically for that use-case. See the editor (when not broken / stopped) at: https://plunker.co/edit/

This is modelled as a two-tier system of `Regions -> Spaces`. `Regions` are the nestable objects that are either horizontal or vertical and have one or more children (except the root that can be empty). `Spaces` are only at leaf nodes and are what handle the drag events when the workspace is not empty. When the workspace is empty, I add an extra child to the root `Region` to handle drag events.

**Comment by CobraFlow** [comment]
I am actually using the containers only currently. I am going to add targets to other controls at a later date. As an example, my 'GrandParent', 'Parent' and 'Child' are nested divs. I have reduced my problem down to propagation. Dropping on the Child propagates to Parent and GrandParent so each one is trying to handle the onDrop.

I've never used plunker. Was that link supposed to go to an example?

Cheers

**Comment by ggoodman** [comment]
No that link is the example. Try dragging files from the sidebar into the
work area.

**Comment by CobraFlow** [comment]
Ok, that is my issue. The GP is the only one with the events enabled due to the pointer-events: none on both the P and C drop containers.
I have disabled the pointer:events style in the stylesheet for now and also added event.stopPropagation() in my event functions so that only the top control under the cursor handles the event..

This works for my situation. I will come back to the stylesheet later to see if I can find a way to handle the <iframe> issue that you mentioned.

Thanks for your help!

**Comment by ggoodman** [comment]
LMK if this isn't enough and I'll re-open.

**Comment by ngiebel** [comment]
Is there a reason that the css could just not be loaded by the module and left up to the using application to add the css if desired? It seems to be very application/use-case specific and not in general required (I could be missing something though). The css could be noted in the readme with use case situations.

Removing it should at least: 
- eliminate CSP concerns
- allow users of the library to selectively use the overlay method when needed, along the lines of adding the current css rules as `.drag-active .use-overlay.drop-container`
- reduce css overhead when rules are not needed

**Comment by ggoodman** [comment]
@ngiebel I think that those are some reasonable ideas. What would you think about a provider-level configuration that determines if the css is injected or not. Alternatively, perhaps `style`s could be added directly to elements conditional on directive attributes.

**Comment by ngiebel** [comment]
@ggoodman 

Having the provider level config option to not load the css should work. Would you want to provide a style sheet with the dist for those that need to conform to certain CSP policies to use or just have a mention of what would need to be added in those situations?

I am not sure that it is possible to achieve the `:before` rule by adding styles directly to a dom element, so you would have to do the dom manipulation manually. It might be easiest to leave it as css and classes.

An option that I can think of for a non-overlay version of a `drop-container` would be to add the class `.drop-container` or `.drop-container-no-overlay` based on an attribute. Possibly that attribute could just be the `drop-container`, defaulting to `true` if undefined so as to not make a breaking change. So the html would end up being something along the lines of `<div drop-container="false"></div>` if you did not need/want the overlay. I cannot think of when it would need to be dynamically configurable, so just using the string value of the attribute should be okay (at least to start with).

**Comment by ngiebel** [comment]
After digging around a bit it looks like the style loading could more easily be determined by using `angular.$$csp().noInlineStyle` instead of using a configuration value.

I was also thinking about what the classes for a `dropContainer` would make the most sense. It might be better to always leave the `.drop-container` class there always and append an additional class to signify overlay use, but that would mean a breaking change due to the css rules changing. Thoughts?

**Comment by ggoodman** [comment]
Hi Nathan,

Can we move this discussion to a github issue? I'm already a bit rusty with
the internals of this lib. It has been running without any major issue in
production for some time. For this reason, I would ask contributors (maybe
you?) to get the ball rolling on a refactor like this.

Geoff
